# Generated by Django 5.2.17 on 2026-10-05 08:24

import django.db.models.deletion
import wedding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ item",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(blank=True, max_length=254)),
                (
                    "invite_code",
                    models.CharField(
                        default=wedding.models.generate_invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("table_number", models.PositiveIntegerField(blank=True, null=True)),
                ("table_name", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuestbookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("message", models.TextField(max_length=1000)),
                ("approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploader_name", models.CharField(blank=True, max_length=120)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("image_url", models.CharField(max_length=500)),
                ("approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="SongRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=120)),
                ("song", models.CharField(max_length=160)),
                ("artist", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeddingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_one", models.CharField(default="Partner One", max_length=80)),
                ("partner_two", models.CharField(default="Partner Two", max_length=80)),
                (
                    "wedding_date",
                    models.DateTimeField(default=wedding.models.default_wedding_date),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="We're getting married!", max_length=160
                    ),
                ),
                ("our_story", models.TextField(blank=True)),
                ("venue_name", models.CharField(blank=True, max_length=160)),
                ("venue_address", models.CharField(blank=True, max_length=255)),
                ("parking_info", models.TextField(blank=True)),
                ("dress_code", models.CharField(blank=True, max_length=160)),
                (
                    "meal_options",
                    models.CharField(
                        default="Chicken,Beef,Vegetarian",
                        help_text="Comma-separated list shown on the RSVP form.",
                        max_length=255,
                    ),
                ),
                ("emergency_contact_name", models.CharField(blank=True, max_length=80)),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=40),
                ),
            ],
            options={
                "verbose_name": "wedding details",
                "verbose_name_plural": "wedding details",
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("attending", models.BooleanField()),
                ("party_size", models.PositiveSmallIntegerField(default=1)),
                ("meal_choice", models.CharField(blank=True, max_length=80)),
                ("dietary_notes", models.CharField(blank=True, max_length=300)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rsvps",
                        to="wedding.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP",
                "ordering": ["-created_at"],
            },
        ),
    ]
